---
- hosts: deploy_servers
  become: yes
  vars_files:
    - /home/jenkins/.ansible/creds.yml
  roles:
    - yuferov.ansible_docker_role
    - yuferov.ansible_webapp_role
    - ansible-nginx-role
...
